### ISSUE TITLE
Nunchuck support

### ISSUE THREAD

**Issue by Queuecumber** [Jacques-Olivier/XWiimote-JG#1]
Hi

You might remember me from this issue here:

https://github.com/dvdhrm/xwiimote/issues/57

Well I finally got around to checking out your code and I was pleasantly surprised by how well it works. I can see in jstest that all the wiimote buttons are detected in jstest

I want to get the nunchuck buttons and joystick working now. I am going to look into doing it myself, but is this something you have any experience doing? Would you accept a PR if I do get it to work?

**Comment by Jacques-Olivier** [comment]
Hi .

Yes I remember ^^ . I get recently new bluetooth keys that work perfectly with my WII/WII U accesories ^^. I will look for the nunchuck too and good joystick support. If you have some solutions for these, don't hesitate to post it here. I will apply it and mention your github name in the code ;) . Thanks again for your help Queuecumber :)

**Comment by Jacques-Olivier** [comment]
Here is a new program that permits you to use the Nunchuck as you wish to use it ;) This program will create a joypad called "XWiimote-Nunchuck-Joypad" : 
-> 9 buttons = 7 buttons from the Wiimote + 2 buttons from the Nunchuck
-> 1 Digital pad (BTN_DPAD_UP, BTN_DPAD_DOWN, BTN_DPAD_LEFT, BTN_DPAD_RIGHT) = Digital pad from the Wiimote
-> 1 analog pad (ABS_HAT0X, ABS_HAT0Y) = Analog pad from the Nunchuck

Thanks again for the idea : I enjoyed creating this new method and testing it with some games :D .

Link of the commit : https://github.com/Jacques-Olivier/XWiimote-JG/commit/398e46bcbb6d3ea461488fdf039d4d811d15e318
Link of the new program directory : https://github.com/Jacques-Olivier/XWiimote-JG/tree/master/xwiimote-nunchuck-joypad

**Comment by Queuecumber** [comment]
I actually added nunchuk support myself to your program, it was not too hard to do

**Comment by Jacques-Olivier** [comment]
With these functions, it is easy indeed =) . The difficulty is only on declarations and initialisations of the equipements. After that, read the data is easy to do.
